apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::034243667166:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-MSG5JD9AMKHU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::034243667166:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-01T16:13:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1533"
  uid: bd8ec09b-c3af-484d-a427-c479b5988ca6
